### ISSUE TITLE
Feature request: type hinting / mypy support

### ISSUE THREAD

**Issue by meshy** [wimglenn/pytest-structlog#15]
Hi! Firstly, thank you for this useful pytest plugin.

I'm writing some code that uses [mypy](http://mypy-lang.org/) to do some reasonably strict type checking, and I've noticed that I get this error when importing from `pytest_structlog`:

```
error: Skipping analyzing 'pytest_structlog': found module but no type hints or library stubs
```

I can work around this by adding a block to my `mypy.ini` file:

```
[mypy-pytest_structlog.*]
ignore_missing_imports = True
```

Ideally however, it'd be nice if this project had type hinting. I notice that this project still has Python 2 in the TravisCI config, so it wouldn't be possible to use the Python 3 type annotations syntax, though there does appear to be [mypy support for Python 2](https://mypy.readthedocs.io/en/stable/python2.html).

There's no important need for this, so no pressure! It's just a "nice to have" from my perspective :slightly_smiling_face:

**Comment by wimglenn** [comment]
Have you considered creating a stub file `pytest_structlog.pyi`?

**Comment by meshy** [comment]
That didn't occur to me. Good idea, thank you!

**Comment by palfrey** [comment]
So, making the stub file will work, but I wouldn't have thought this is actually closed? Would you be interested in a PR fixing this?

**Comment by wimglenn** [comment]
Sure, with the caveat that the PR must also add a pyright or mypy run into the CI (in .github/workflows)

**Comment by palfrey** [comment]
@wimglenn https://github.com/wimglenn/pytest-structlog/pull/27 does all that. Note that it doesn't work for 2.7 at all right now (but neither does the overall build), but wasn't sure of your thoughts on support there.
