### ISSUE TITLE
pytest-structlog catches events with "exception" level while they display "error" level in structlog

### ISSUE THREAD

**Issue by b0g3r** [wimglenn/pytest-structlog#30]
Latest version of structlog changes behavior of `logger.exception` a little bit ([23.3](https://github.com/hynek/structlog/issues/571), [24.1](https://github.com/hynek/structlog/issues/584)), and now they transform level to "error" in one of the processors, as far as I understand. I would like to see the same behavior in the pytest-structlog, to more accurately test displayable events.

For now pytest-structlog catches `level=exception` event for logger.exception() calls with stdlib bound logger. I will attach reproducible example in draft PR: https://github.com/wimglenn/pytest-structlog/pull/31

**Comment by wimglenn** [comment]
Thanks for the reproducer - I confirm something changed between structlog 23.2 and 23.3 causing this. It looks like adding 

```
    if method_name == "exception":
        method_name = "error"
```

into `StructuredLogCapture.process` would fix this issue, although I'd like to understand better the root cause first..
