### ISSUE TITLE
log captures events before processing, not after

### ISSUE THREAD

**Issue by palfrey** [wimglenn/pytest-structlog#34]
I've got a fairly extensive structlog config, including things that drop events that match particular patterns. I was trying to test this code with pytest-structlog, and it seems to not work? I'm guessing because of either `structlog.configure` being patched out (and so my config not getting applied) or the capture bits happening before my functions.

Any thoughts on this? I've worked around this at the moment with `capsys` and parsing of JSON logs, but would prefer a fixture here that can capture at the end of a processing queue.

**Comment by wimglenn** [comment]
I have a proposal described [here](https://github.com/wimglenn/pytest-structlog/tree/keep?tab=readme-ov-file#advanced-configuration) in https://github.com/wimglenn/pytest-structlog/pull/35 which you can install from test PyPI

    pip install --index-url=https://test.pypi.org/simple 'pytest-structlog==0.10'

Let me know what you think.

**Comment by wimglenn** [comment]
In [pytest-structlog 1.0](https://pypi.org/project/pytest-structlog/1.0/) it is possible to keep pre-existing processors by using the new `--structlog-evict` CLI option, or by adding something like this in your `pyproject.toml`:

```
[tool.pytest.ini_options]
structlog_evict = ["TimeStamper", "JSONRender"]
```

Let me know if you have any troubles.
