### ISSUE TITLE
Rights to push new feature

### ISSUE THREAD

**Issue by Rashguir** [wimglenn/pytest-structlog#4]
Hi,

I've tried to push a branch and submit a pull request but got this message :
```
ERROR: Permission to wimglenn/pytest-structlog.git denied to Rashguir
```

Could you please consider opening this repository.

Thank you

**Comment by wimglenn** [comment]
Forking and pushing to your fork is the usual workflow. You don't need to create branches on this one.

**Comment by Rashguir** [comment]
ok thanks :) i'm not used to this workflow.
#5 is what i wanted to add ;)
